server:
  port: 9090

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]:
        id: user-service
        uri: http://localhost:8070
        predicates:
          - Path=/user/**
      routes[1]:
        id: employee-service
        uri: http://localhost:8080
        predicates:
          - Path=/employee/**