server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/emp

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka